// Generated by https://quicktype.io

/*
ProductoModel productoModelFromJson(String str) =>
    ProductoModel.fromJson(json.decode(str));

String productoModelToJson(ProductoModel data) => json.encode(data.toJson());
*/
/*
class Productos {
  List<Producto> items = [];
  //List<Producto> items = new List();

  Productos();

  Productos.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final producto = new Producto.fromJsonMap(item);
      items.add(producto);
    }
  }
}
*/

class Gastos {
  List<Gasto> items = [];
  //List<Gasto> items = new List();

  Gastos();

  Gastos.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final gasto = new Gasto.fromJsonMap(item);
      items.add(gasto);
    }
  }
}

/*
pcode: "0001234",
preferencia: "AREF-CODIGO",
pdescribe: "ACarnes de Primera",
pdepartamento: "",
pventa1: 5.480000019073486,
pventa2: 6.91,
pventa3: 5.32,
pventa4: 0,
pventa5: 0,
pempaque: "1",
pmedida: "UNI",
pmedempaque: "N/A",
pexiste: 2,
pintercode: "CODIGODEBARRA",
Pdatevoid: "31/12/2019",
pmoneydif: 1,
ptasac: 18.8
*/
/*
//TODOS ESTOS SON DOUBLE
PRECIO": 0.22895,
        "PRECIO_MM": 0.01,
        "TOTAL": 0.27,
        "TOTALENCA": 44.71,
        "TOTAL_MM": 0.01,
        "TASA":27.2222
*/
class Gasto {
  String numero;
  String codcli;
  String nomcli;
  String codart;
  String nomart;
  String desart;
  int posren;
  double precio;
  double precioMm;
  double total;
  double totalenca;
  double totalMm;
  DateTime emitida;
  DateTime fechaDesde;
  DateTime fechaHasta;
  String tasa;
  String mes;
  String anio;

  Gasto({
    this.numero,
    this.codcli,
    this.nomcli,
    this.codart,
    this.nomart,
    this.desart,
    this.posren,
    this.precio,
    this.precioMm,
    this.total,
    this.totalenca,
    this.totalMm,
    this.emitida,
    this.fechaDesde,
    this.fechaHasta,
    this.tasa,
    this.mes,
    this.anio,
  });
  //Gasto.fromJsonMap(Map<String, dynamic> json) {
  //pventa1 = json['pventa1'] / 1;
  Gasto.fromJsonMap(Map<String, dynamic> json) {
    numero = json["NUMERO"];
    codcli = json["CODCLI"];
    nomcli = json["NOMCLI"];
    codart = json["CODART"];
    nomart = json["NOMART"];
    desart = json["DESART"];
    posren = json["POSREN"];
    precio = json["PRECIO"] / 1;
    precioMm = json["PRECIO_MM"] / 1;
    total = json["TOTAL"] / 1;
    totalenca = json["TOTALENCA"]?.toDouble();
    totalMm = json["TOTAL_MM"] / 1;
    emitida = DateTime.parse(json["EMITIDA"]);
    fechaDesde = DateTime.parse(json["FECHA_DESDE"]);
    fechaHasta = DateTime.parse(json["FECHA_HASTA"]);
    tasa = json["TASA"];
    mes = json["MES"];
    anio = json["ANIO"];
    //       ptasac = json['ptasac'] / 1;
  }
/*
  Map<String, dynamic> toJson() => {
        "NUMERO": numero,
        "CODCLI": codcli,
        "NOMCLI": nomcli,
        "CODART": codart,
        "NOMART": nomart,
        "DESART": desart,
        "POSREN": posren,
        "PRECIO": precio,
        "PRECIO_MM": precioMm,
        "TOTAL": total,
        "TOTALENCA": totalenca,
        "TOTAL_MM": totalMm,
        "EMITIDA": emitida.toIso8601String(),
        "FECHA_DESDE": fechaDesde.toIso8601String(),
        "FECHA_HASTA": fechaHasta.toIso8601String(),
        "TASA": tasa,
        "MES": mes,
        "ANIO": anio,
      };
*/
/*
  Gasto.fromJsonMap(Map<String, dynamic> json) {
    pcode = json['pcode'];
    pdescribe = json['pdescribe'];
    preferencia = json['preferencia'];
    pdepartamento = json['pdepartamento'];
    pventa1 = json['pventa1'] / 1;
    pventa2 = json['pventa2'] / 1;
    pventa3 = json['pventa3'] / 1;
    pventa4 = json['pventa4'] / 1;
    pventa5 = json['pventa5'] / 1;
    pempaque = json['pempaque'];
    pmedida = json['pmedida'];
    pmedempaque = json['pmedempaque'];
    pexiste = json['pexiste'] / 1;
    pintercode = json['pintercode'];
    pmoneydif = json['pmoneydif'];
    ptasac = json['ptasac'] / 1;
  }

*/
  String get valor => null;

  getImagen1() {
    if (nomcli == null) {
      return "https://gruposriojanos.com/wp-content/uploads/2019/10/no-imagen-110.jpg";
    } else {
      // print (posterPath);
      //return "https://image.tmdb.org/t/p/w500/$pdescribe";
      //
      //return "https://gruposriojanos.com/wp-content/uploads/2019/10/no-imagen-110.jpg";
      return "https://akrocard.com/wp-content/uploads/2016/06/EAN8.png";
    }
  }

  getFondoImagen1() {
    if (nomart == null) {
      return "https://gruposriojanos.com/wp-content/uploads/2019/10/no-imagen-110.jpg";
    } else {
      // print (posterPath);
      return "https://image.tmdb.org/t/p/w500/$nomart";
    }
  }
}
